// image data
#define TEXSIZ_SYSTEM_W 1024
#define TEXSIZ_SYSTEM_H 1024
#define TEXSIZ_SYSTEM_WH 1024, 1024
#define TEXPOS_SYSTEM_BOXWHITE_X 0
#define TEXPOS_SYSTEM_BOXWHITE_Y 0
#define TEXPOS_SYSTEM_BOXWHITE_W 32
#define TEXPOS_SYSTEM_BOXWHITE_H 32
#define TEXPOS_SYSTEM_BOXWHITE_XYWH 0, 0, 32, 32
#define TEXPOS_SYSTEM_BOXBASIC_X 0
#define TEXPOS_SYSTEM_BOXBASIC_Y 34
#define TEXPOS_SYSTEM_BOXBASIC_W 41
#define TEXPOS_SYSTEM_BOXBASIC_H 41
#define TEXPOS_SYSTEM_BOXBASIC_XYWH 0, 34, 41, 41
#define TEXPOS_SYSTEM_BUTTONBASICNORMAL_X 43
#define TEXPOS_SYSTEM_BUTTONBASICNORMAL_Y 0
#define TEXPOS_SYSTEM_BUTTONBASICNORMAL_W 41
#define TEXPOS_SYSTEM_BUTTONBASICNORMAL_H 49
#define TEXPOS_SYSTEM_BUTTONBASICNORMAL_XYWH 43, 0, 41, 49
#define TEXPOS_SYSTEM_BUTTONBASICACTIVE_X 86
#define TEXPOS_SYSTEM_BUTTONBASICACTIVE_Y 0
#define TEXPOS_SYSTEM_BUTTONBASICACTIVE_W 41
#define TEXPOS_SYSTEM_BUTTONBASICACTIVE_H 49
#define TEXPOS_SYSTEM_BUTTONBASICACTIVE_XYWH 86, 0, 41, 49
#define TEXPOS_SYSTEM_BUTTONBASICSELECT_X 129
#define TEXPOS_SYSTEM_BUTTONBASICSELECT_Y 0
#define TEXPOS_SYSTEM_BUTTONBASICSELECT_W 41
#define TEXPOS_SYSTEM_BUTTONBASICSELECT_H 49
#define TEXPOS_SYSTEM_BUTTONBASICSELECT_XYWH 129, 0, 41, 49
#define TEXPOS_SYSTEM_BUTTONBASICINACTIVE_X 172
#define TEXPOS_SYSTEM_BUTTONBASICINACTIVE_Y 0
#define TEXPOS_SYSTEM_BUTTONBASICINACTIVE_W 41
#define TEXPOS_SYSTEM_BUTTONBASICINACTIVE_H 49
#define TEXPOS_SYSTEM_BUTTONBASICINACTIVE_XYWH 172, 0, 41, 49
#define TEXPOS_SYSTEM_BUTTONPICKERNORMAL_X 43
#define TEXPOS_SYSTEM_BUTTONPICKERNORMAL_Y 51
#define TEXPOS_SYSTEM_BUTTONPICKERNORMAL_W 56
#define TEXPOS_SYSTEM_BUTTONPICKERNORMAL_H 60
#define TEXPOS_SYSTEM_BUTTONPICKERNORMAL_XYWH 43, 51, 56, 60
#define TEXPOS_SYSTEM_BUTTONPICKERACTIVE_X 101
#define TEXPOS_SYSTEM_BUTTONPICKERACTIVE_Y 51
#define TEXPOS_SYSTEM_BUTTONPICKERACTIVE_W 56
#define TEXPOS_SYSTEM_BUTTONPICKERACTIVE_H 60
#define TEXPOS_SYSTEM_BUTTONPICKERACTIVE_XYWH 101, 51, 56, 60
#define TEXPOS_SYSTEM_BUTTONPICKERSELECT_X 159
#define TEXPOS_SYSTEM_BUTTONPICKERSELECT_Y 51
#define TEXPOS_SYSTEM_BUTTONPICKERSELECT_W 56
#define TEXPOS_SYSTEM_BUTTONPICKERSELECT_H 60
#define TEXPOS_SYSTEM_BUTTONPICKERSELECT_XYWH 159, 51, 56, 60
#define TEXPOS_SYSTEM_BUTTONPICKERINACTIVE_X 217
#define TEXPOS_SYSTEM_BUTTONPICKERINACTIVE_Y 51
#define TEXPOS_SYSTEM_BUTTONPICKERINACTIVE_W 56
#define TEXPOS_SYSTEM_BUTTONPICKERINACTIVE_H 60
#define TEXPOS_SYSTEM_BUTTONPICKERINACTIVE_XYWH 217, 51, 56, 60
#define TEXPOS_SYSTEM_BUTTONCTRLUPNORMAL_X 0
#define TEXPOS_SYSTEM_BUTTONCTRLUPNORMAL_Y 113
#define TEXPOS_SYSTEM_BUTTONCTRLUPNORMAL_W 68
#define TEXPOS_SYSTEM_BUTTONCTRLUPNORMAL_H 96
#define TEXPOS_SYSTEM_BUTTONCTRLUPNORMAL_XYWH 0, 113, 68, 96
#define TEXPOS_SYSTEM_BUTTONCTRLDNNORMAL_X 94
#define TEXPOS_SYSTEM_BUTTONCTRLDNNORMAL_Y 187
#define TEXPOS_SYSTEM_BUTTONCTRLDNNORMAL_W 68
#define TEXPOS_SYSTEM_BUTTONCTRLDNNORMAL_H 96
#define TEXPOS_SYSTEM_BUTTONCTRLDNNORMAL_XYWH 94, 187, 68, 96
#define TEXPOS_SYSTEM_BUTTONCTRLRTNORMAL_X 70
#define TEXPOS_SYSTEM_BUTTONCTRLRTNORMAL_Y 113
#define TEXPOS_SYSTEM_BUTTONCTRLRTNORMAL_W 92
#define TEXPOS_SYSTEM_BUTTONCTRLRTNORMAL_H 72
#define TEXPOS_SYSTEM_BUTTONCTRLRTNORMAL_XYWH 70, 113, 92, 72
#define TEXPOS_SYSTEM_BUTTONCTRLLTNORMAL_X 0
#define TEXPOS_SYSTEM_BUTTONCTRLLTNORMAL_Y 211
#define TEXPOS_SYSTEM_BUTTONCTRLLTNORMAL_W 92
#define TEXPOS_SYSTEM_BUTTONCTRLLTNORMAL_H 72
#define TEXPOS_SYSTEM_BUTTONCTRLLTNORMAL_XYWH 0, 211, 92, 72
#define TEXPOS_SYSTEM_BUTTONCTRLUPACTIVE_X 164
#define TEXPOS_SYSTEM_BUTTONCTRLUPACTIVE_Y 113
#define TEXPOS_SYSTEM_BUTTONCTRLUPACTIVE_W 68
#define TEXPOS_SYSTEM_BUTTONCTRLUPACTIVE_H 96
#define TEXPOS_SYSTEM_BUTTONCTRLUPACTIVE_XYWH 164, 113, 68, 96
#define TEXPOS_SYSTEM_BUTTONCTRLDNACTIVE_X 258
#define TEXPOS_SYSTEM_BUTTONCTRLDNACTIVE_Y 187
#define TEXPOS_SYSTEM_BUTTONCTRLDNACTIVE_W 68
#define TEXPOS_SYSTEM_BUTTONCTRLDNACTIVE_H 96
#define TEXPOS_SYSTEM_BUTTONCTRLDNACTIVE_XYWH 258, 187, 68, 96
#define TEXPOS_SYSTEM_BUTTONCTRLRTACTIVE_X 234
#define TEXPOS_SYSTEM_BUTTONCTRLRTACTIVE_Y 113
#define TEXPOS_SYSTEM_BUTTONCTRLRTACTIVE_W 92
#define TEXPOS_SYSTEM_BUTTONCTRLRTACTIVE_H 72
#define TEXPOS_SYSTEM_BUTTONCTRLRTACTIVE_XYWH 234, 113, 92, 72
#define TEXPOS_SYSTEM_BUTTONCTRLLTACTIVE_X 164
#define TEXPOS_SYSTEM_BUTTONCTRLLTACTIVE_Y 211
#define TEXPOS_SYSTEM_BUTTONCTRLLTACTIVE_W 92
#define TEXPOS_SYSTEM_BUTTONCTRLLTACTIVE_H 72
#define TEXPOS_SYSTEM_BUTTONCTRLLTACTIVE_XYWH 164, 211, 92, 72
#define TEXPOS_SYSTEM_BUTTONCTRLBTNNORMAL_X 215
#define TEXPOS_SYSTEM_BUTTONCTRLBTNNORMAL_Y 0
#define TEXPOS_SYSTEM_BUTTONCTRLBTNNORMAL_W 41
#define TEXPOS_SYSTEM_BUTTONCTRLBTNNORMAL_H 49
#define TEXPOS_SYSTEM_BUTTONCTRLBTNNORMAL_XYWH 215, 0, 41, 49
#define TEXPOS_SYSTEM_BUTTONCTRLBTNACTIVE_X 258
#define TEXPOS_SYSTEM_BUTTONCTRLBTNACTIVE_Y 0
#define TEXPOS_SYSTEM_BUTTONCTRLBTNACTIVE_W 41
#define TEXPOS_SYSTEM_BUTTONCTRLBTNACTIVE_H 49
#define TEXPOS_SYSTEM_BUTTONCTRLBTNACTIVE_XYWH 258, 0, 41, 49
#define TEXPOS_SYSTEM_FONTABCD_X 0
#define TEXPOS_SYSTEM_FONTABCD_Y 285
#define TEXPOS_SYSTEM_FONTABCD_W 320
#define TEXPOS_SYSTEM_FONTABCD_H 180
#define TEXPOS_SYSTEM_FONTABCD_XYWH 0, 285, 320, 180
#define TEXPOS_SYSTEM_FONTHIRA_X 0
#define TEXPOS_SYSTEM_FONTHIRA_Y 467
#define TEXPOS_SYSTEM_FONTHIRA_W 320
#define TEXPOS_SYSTEM_FONTHIRA_H 180
#define TEXPOS_SYSTEM_FONTHIRA_XYWH 0, 467, 320, 180
#define TEXPOS_SYSTEM_FONTKATA_X 0
#define TEXPOS_SYSTEM_FONTKATA_Y 649
#define TEXPOS_SYSTEM_FONTKATA_W 320
#define TEXPOS_SYSTEM_FONTKATA_H 180
#define TEXPOS_SYSTEM_FONTKATA_XYWH 0, 649, 320, 180
